---
intros:

outros:


walks:
  abolishice:
    category: long
    loops: 7
  appreciate:
    category: social
  art:
    category: inactive
  bike:
    category: actions
  bowl:
    category: actions
  cartwheel:
    category: actions
    loops: 4
  chestbump:
    category: actions
  cocoadome:
    category: funny
  converse:
    category: social
  corgi:
    category: funny
    loops: 8
  cube:
    category: trip
    loops: 7
    audio: trip.wav
  croix:
    category: funny
    loops: 6
    audio: hydrate.wav
  crabwalk:
    category: actions
  crawl:
    category: actions
  dance1:
    category: dance
    loops: 10
  dance3:
    category: dance
  dance4:
    category: dance
    loops: 10
  dance5:
    category: dance
  dance8:
    category: dance
  dance9:
    category: dance
    audio: dance6.wav
  dancebattle:
    category: inactive
    loops: 1
  dots:
    category: trip
    loops: 10
    audio: trip.wav
  elephant:
    category: animals
  fartbox:
    category: inactive
  fall:
    category: actions
  flying:
    category: actions
  frida:
    category: trip
    loops: 10
    audio: trip.wav
  hammer-time:
    category: inactive
    loops: 1
  handstand:
    category: actions
  highfive:
    category: social
  horse:
    category: inactive
  horsebackriding:
    category: actions
  hug:
    category: social
  hug3:
    category: social
  hug4:
    category: social
  hug5:
    category: social
  hydrate:
    category: actions
  jazzhands:
    category: inactive
  jump:
    category: actions
  leapfrog:
    category: actions
  meditate:
    category: inactive
    loops: 60
  natureappreciate:
    category: inactive
    loops: 7
  nyan:
    category: funny
    loops: 5
  partyrock:
    category: inactive
  piggyback:
    category: actions
  pose:
    category: funny
  presentation:
    category: inactive
  race:
    category: actions
    loops: 1
  rainbow_heart:
    category: trip
    loops: 5
    audio: trip.wav
  resilience:
    category: inactive
    loops: 17
  rowboat:
    category: actions
  run:
    category: actions
  ski:
    category: actions
  sleep:
    category: inactive
  sloth:
    category: animals
  somersault:
    category: actions
  surf:
    category: actions
  swim:
    category: actions
  tag:
    category: social
  teleport:
    category: funny
  timewarp:
    category: inactive
    loops: 6
  titdance:
    category: trip
    loops: 8
    audio: trip.wav
  triptrap:
    category: trip
  turtle:
    category: animals
    loops: 12
  unicycle:
    category: actions
  vogue1:
    category: inactive
    audio: dance7.wav
  walkdress:
    category: normal
  walkpants:
    category: normal
  wheelbarrow:
    category: social
  why-cross:
    category: mindful
    loops: 1
  wok:
    category: funny
  walkingtogether:
    category: social
  westworldmaze:
    category: inactive
  werewolf:
    category: action
  weirddog:
    category: trip
    loops: 10
    audio: trip.wav
  weirdeyes:
    category: trip
    loops: 6
    audio: trip.wav
  wizard:
    category: funny
  yoga1:
    category: inactive
    loops: 1
  yoga2:
    category: inactive
    loops: 1
  yoga3:
    category: inactive
    loops: 1
  yoga4:
    category: inactive
    loops: 1
  yoga5:
    category: inactive
    loops: 1
  yoga6:
    category: inactive
    loops: 1
  yoga7:
    category: inactive
    loops: 1
  zebra:
    category: trip
    loops: 15
    audio: trip.wav
  zombie:
    category: actions


# normal
# actions
# animals
# dance
# social
# funny
# long
# mindful

weights:
  all:
    _: 1
  monday:
    normal: 1
  tuesday:
    normal: 1
    actions: 2
    animals: 2
  wednesday:
    normal: 1
    actions: 3
    animals: 3
    social: 2
  wednesday-night:
    normal: 1
    actions: 3
    animals: 3
    social: 2
    trip: 1
  thursday:
    normal: 1
    actions: 3
    animals: 2
    social: 3
    funny: 2
    trip: 1
  friday:
    actions: 3
    animals: 1
    social: 3
    funny: 4
    long: 1
    mindful: 1
  saturday:
    actions: 3
    animals: 1
    social: 3
    funny: 3
    long: 2
    mindful: 1
  saturday-night:
    actions: 4
    animals: 1
    social: 3
    funny: 4
    long: 1
    mindful: 1
    dance: 4
    trip: 4


schedule:
  - start: '2018-07-09T00:00:00'
    weights: monday
  - start: '2018-07-10T00:00:00'
    weights: tuesday
  - start: '2018-07-11T00:00:00'
    weights: wednesday
  - start: '2018-07-11T22:00:00'
    weights: wednesday-night
  - start: '2018-07-12T06:00:00'
    weights: thursday
  - start: '2018-07-13T00:00:00'
    weights: friday
  - start: '2018-07-14T00:00:00'
    weights: saturday
  - start: '2018-07-14T19:00:00'
    weights: saturday-night
