---
intros:

outros:

walks:
  abolishice:
    category: rare
    loops: 7
  aircello:
    category: dance
    loops: 1
  airdrum:
    category: dance
    loops: 1
  airguitar_wed1:
    category: dance
    loops: 1
  airguitar_wed2:
    category: dance
    loops: 1
  airguitar_wed3:
    category: dance
    loops: 1
  airguitar_wed4:
    category: dance
    loops: 1
  airguitar_thu1:
    category: dance
    loops: 1
  airguitar_thu2:
    category: dance
    loops: 1
  airguitar_thu3:
    category: dance
    loops: 1
  airguitar_thu4:
    category: dance
    loops: 1
  airguitar_fri1:
    category: dance
    loops: 1
  airguitar_fri2:
    category: dance
    loops: 1
  airguitar_fri3:
    category: dance
    loops: 1
  airguitar_fri4:
    category: dance
    loops: 1
  airguitar_sat1:
    category: dance
    loops: 1
  airguitar_sat2:
    category: dance
    loops: 1
  airguitar_sat3:
    category: dance
    loops: 1
  airguitar_sat4:
    category: dance
    loops: 1
  airsax:
    category: dance
    loops: 1
  airtrombone:
    category: dance
    loops: 1
  applaud:
    category: actions
    loops: 1
  appreciate:
    category: social
  babyshark:
    category: rare
    loops: 1
  baseball:
    category: actions
    loops: 1
  bike:
    category: actions
  bird:
    category: animals
    loops: 1
  bowl:
    category: actions
    loops: 1
  burp:
    category: funny
    loops: 1
  carryHeavy:
    category: actions
    loops: 1
  cartwheel:
    category: actions
    loops: 4
  cat:
    category: animals
    loops: 1
  chestbump:
    category: actions
  clickHeels:
    category: actions
    loops: 1
  cocoadome:
    category: inactive
  conga:
    category: dance
    loops: 1
  converse:
    category: social
  cow:
    category: animals
    loops: 1
  cowboy:
    category: actions
    loops: 1
  crabwalk:
    category: actions
  crawl:
    category: actions
  crossingguard:
    category: actions
    loops: 1
  crossingguard-wizard:
    category: actions
    loops: 1
  cry:
    category: actions
    loops: 1
  dab:
    category: dance
    loops: 1
  daftpunk-1:
    category: rare
    loops: 1
  daftpunk-2:
    category: rare
    loops: 1
  daftpunk-3:
    category: rare
    loops: 1
  daftpunk-4:
    category: rare
    loops: 1
  dance-hustle:
    category: dance
    loops: 1
  dance-macarena:
    category: dance
    loops: 1
  dance-twerk:
    category: dance
    loops: 1
  dance-twist:
    category: dance
    loops: 1
  dancemove-chacha:
    category: dance
    loops: 1
  dancemove-cupidshuffle:
    category: dance
    loops: 1
  dancemove-hokeypokey:
    category: dance
    loops: 1
  dancemove-whipnaenae:
    category: dance
    loops: 3
  dfv:
    category: actions
    loops: 1
  dog:
    category: animals
    loops: 1
  duck:
    category: animals
    loops: 1
  fall:
    category: actions
    loops: 1
  fartbox:
    category: inactive
  flying:
    category: actions
  frankensteinsmonsterwalk:
    category: actions
    loops: 1
  getschwifty:
    category: rare
    loops: 1
  ghost:
    category: actions
    loops: 1
  gif-corgi:
    category: funny
    loops: 8
  gif-cube:
    category: inactive
    loops: 7
    audio: trip.wav
  gif-dots:
    category: inactive
    loops: 10
    audio: trip.wav
  gif-frida:
    category: inactive
    loops: 7
    audio: trip.wav
  gif-nyan:
    category: funny
    loops: 5
  gif-rainbow_heart:
    category: inactive
    loops: 3
    audio: trip.wav
  gif-weirddog:
    category: inactive
    loops: 10
    audio: trip.wav
  gif-weirdeyes:
    category: inactive
    loops: 6
    audio: trip.wav
  gif-zebra:
    category: inactive
    loops: 15
    audio: trip.wav
  golf:
    category: actions
    loops: 1
  hadouken:
    category: funny
    loops: 1
  hammertime:
    category: dance
    loops: 1
  handshake:
    category: actions
    loops: 1
  handstand:
    category: actions
  headpatbellyrub:
    category: actions
    loops: 1
  highfive:
    category: social
  home:
    category: fin
  hop:
    category: actions
    loops: 1
  hopscotch:
    category: actions
    loops: 1
  horsebackriding:
    category: actions
  hug:
    category: social
  hug3:
    category: social
  hug4:
    category: social
  hug5:
    category: social
  hurdle:
    category: actions
    loops: 1
  hydrate:
    category: actions
  invisibleCar:
    category: actions
    loops: 1
  inw:
    category: inactive
    audio: seacompression.wav
  jump:
    category: actions
  jumpingjacks:
    category: actions
    loops: 1
  jumprope:
    category: actions
    loops: 1
  kangaroo:
    category: animals
    loops: 1
  karaoke-ABC:
    category: dance
    loops: 1
  karaoke-heyYa:
    category: dance
    loops: 1
  karaoke-hookedOnAFeeling:
    category: dance
    loops: 1
  karaoke-iAmTheWalrus:
    category: dance
    loops: 1
  karaoke-iWantItThatWay:
    category: dance
    loops: 1
  karaoke-loveShack:
    category: dance
    loops: 1
  karaoke-returnOfTheMack:
    category: dance
    loops: 1
  karaoke-sayMyName:
    category: dance
    loops: 1
  karaoke-sinceYouBeenGone:
    category: dance
    loops: 1
  karaoke-sweetHomeAlabama:
    category: dance
    loops: 1
  karaoke-totalEclipse:
    category: dance
    loops: 1
  karaoke-tubthumping:
    category: dance
    loops: 1
  karaoke-wannaDance:
    category: dance
    loops: 1
  laugh:
    category: actions
    loops: 1
  leapfrog:
    category: actions
  longjump:
    category: actions
    loops: 1
  meditationWednesday:
    loops: 1
  meditationThursday:
    loops: 1
  meditationFriday:
    loops: 1
  meditationSaturday:
    loops: 1
  mime:
    category: actions
    loops: 1
  monkey:
    category: animals
    loops: 1
  orderbyheight:
    category: social
    loops: 1
  penguin:
    category: animals
    loops: 1
  pickUpMoop:
    category: actions
    loops: 1
  piggyback:
    category: actions
  poetry-dreams:
    category: rare
    loops: 1
  poetry-hope:
    category: rare
    loops: 1
  poetry-loveAfterLove:
    category: rare
    loops: 1
  poetry-meFromMyself:
    category: rare
    loops: 1
  poetry-theWindOneBrilliantDay:
    category: rare
    loops: 1
  pose:
    category: funny
  propose:
    category: actions
    loops: 1
  pushup:
    category: actions
    loops: 1
  race:
    category: actions
    loops: 1
  raptor:
    loops: 1
  rickroll:
    loops: 1
  rowboat:
    category: actions
  rps1:
    loops: 1
    audio: rps.wav
  rps2:
    loops: 1
    audio: rps.wav
  rps3:
    loops: 1
    audio: rps.wav
  rps4:
    loops: 1
    audio: rps.wav
  rps5:
    loops: 1
    audio: rps.wav
  rps6:
    loops: 1
    audio: rps.wav
  rps7:
    loops: 1
    audio: rps.wav
  rps8:
    loops: 1
    audio: rps.wav
  rps9:
    loops: 1
    audio: rps.wav
  rps10:
    loops: 1
    audio: rps.wav
  rps11:
    loops: 1
    audio: rps.wav
  rps12:
    loops: 1
    audio: rps.wav
  rps13:
    loops: 1
    audio: rps.wav
  rps14:
    loops: 1
    audio: rps.wav
  rps15:
    loops: 1
    audio: rps.wav
  rps16:
    loops: 1
    audio: rps.wav
  rps17:
    loops: 1
    audio: rps.wav
  rps18:
    loops: 1
    audio: rps.wav
  rps19:
    loops: 1
    audio: rps.wav
  rps20:
    loops: 1
    audio: rps.wav
  rps21:
    loops: 1
    audio: rps.wav
  rps22:
    loops: 1
    audio: rps.wav
  rps23:
    loops: 1
    audio: rps.wav
  rps24:
    loops: 1
    audio: rps.wav
  rps25:
    loops: 1
    audio: rps.wav
  rps26:
    loops: 1
    audio: rps.wav
  rps27:
    loops: 1
    audio: rps.wav
  run:
    category: actions
  screenless:
    category: rare
    loops: 1
  ski:
    category: actions
  skip:
    category: actions
    loops: 1
  sleep:
    category: inactive
  sloth:
    category: animals
  smile:
    category: actions
    loops: 1
  snake:
    category: animals
    loops: 1
  snap:
    category: actions
    loops: 1
  sneeze:
    category: actions
    loops: 1
  somersault:
    category: actions
    loops: 1
  spaceodyssea:
    category: inactive
    frame_delay: 25.0
    audio: seacompression.wav
  spin:
    category: actions
    loops: 1
  staringContest:
    category: social
    loops: 1
  surf:
    category: actions
  swashbuckle:
    category: social
    loops: 1
  sweep:
    category: actions
    loops: 1
  swim:
    category: actions
  tag:
    category: social
  tapDance:
    category: actions
    loops: 1
  teamCheer:
    category: actions
    loops: 1
  teleport:
    category: funny
  thankRangers:
    loops: 1
  tightrope:
    category: actions
    loops: 1
  tongueTwister1:
    category: actions
    loops: 2
    audio: tongueTwister.wav
  tongueTwister2:
    category: actions
    loops: 2
    audio: tongueTwister.wav
  tongueTwister3:
    category: actions
    loops: 2
    audio: tongueTwister.wav
  tongueTwister4:
    category: actions
    loops: 2
    audio: tongueTwister.wav
  toothbrush:
    category: actions
    loops: 1
  trip-cauliflower:
    category: trip
    loops: 10
    audio: trip.wav
  trip-cauliflower_mask:
    category: trip
    loops: 10
    audio: trip.wav
  trip-cube:
    category: trip
    loops: 5
    audio: trip.wav
  trip-cube_mask:
    category: trip
    loops: 5
    audio: trip.wav
  trip-dizzy:
    category: trip
    loops: 5
    audio: trip.wav
  trip-dizzy_mask:
    category: trip
    loops: 5
    audio: trip.wav
  trip-dots:
    category: trip
    loops: 10
    audio: trip.wav
  trip-dots_mask:
    category: trip
    loops: 10
    audio: trip.wav
  trip-glorbs:
    category: trip
    loops: 1
    audio: trip.wav
  trip-glorbs_mask:
    category: trip
    loops: 1
    audio: trip.wav
  trip-grillz:
    category: trip
    loops: 2
    audio: trip.wav
  trip-grillz_mask:
    category: trip
    loops: 2
    audio: trip.wav
  trip-jellyRainbow:
    category: trip
    loops: 4
    audio: trip.wav
  trip-jellyRainbow_mask:
    category: trip
    loops: 4
    audio: trip.wav
  trip-lasercats:
    category: trip
    loops: 4
    audio: trip.wav
  trip-lavalamp:
    category: trip
    loops: 4
    audio: trip.wav
  trip-lavalamp_mask:
    category: trip
    loops: 4
    audio: trip.wav
  trip-plaidSpeed:
    category: trip
    loops: 7
    audio: trip.wav
  trip-plaidSpeed_mask:
    category: trip
    loops: 7
    audio: trip.wav
  trip-rainbowKnot:
    category: trip
    loops: 8
    audio: trip.wav
  trip-rainbowKnot_mask:
    category: trip
    loops: 8
    audio: trip.wav
  trip-rainbowTunnel:
    category: trip
    loops: 5
    audio: trip.wav
  trip-rainbowTunnel_mask:
    category: trip
    loops: 5
    audio: trip.wav
  trip-rainbowWiggles:
    category: trip
    loops: 2
    audio: trip.wav
  trip-rainbowWiggles_mask:
    category: trip
    loops: 2
    audio: trip.wav
  trip-redEye:
    category: trip
    loops: 3
    audio: trip.wav
  trip-redEye_mask:
    category: trip
    loops: 3
    audio: trip.wav
  trip-scopey:
    category: trip
    loops: 5
    audio: trip.wav
  trip-scopey_mask:
    category: trip
    loops: 5
    audio: trip.wav
  trip-warpSpeed:
    category: trip
    loops: 7
    audio: trip.wav
  trip-warpSpeed_mask:
    category: trip
    loops: 7
    audio: trip.wav
  trip-weirdEyes:
    category: trip
    loops: 3
    audio: trip.wav
  trip-weirdEyes_mask:
    category: trip
    loops: 3
    audio: trip.wav
  trip-weirdStatic:
    category: trip
    loops: 10
    audio: trip.wav
  trip-weirdStatic_mask:
    category: trip
    loops: 10
    audio: trip.wav
  trip-zebra:
    category: trip
    loops: 11
    audio: trip.wav
  trip-zebraSphere:
    category: trip
    loops: 20
    audio: trip.wav
  trip-zebra_mask:
    category: trip
    loops: 11
    audio: trip.wav
  trip-zebraSphere_mask:
    category: trip
    loops: 20
    audio: trip.wav
  turtle:
    category: animals
    loops: 12
  unicycle:
    category: inactive
  vacuum:
    category: actions
    loops: 3
  walkBackwards:
    category: actions
    loops: 3
  walkdress:
    category: normal
  walkingLunge:
    category: actions
    loops: 1
  walkpants:
    category: normal
  werewolf:
    category: animals
  wheelbarrow:
    category: actions
  whistle:
    category: actions
    loops: 1
  why-cross:
    category: rare
    loops: 1
  witch:
    category: funny
    loops: 1
  wizard:
    category: funny
  wok:
    category: funny
  workoutWednesday:
    loops: 1
  workoutThursday:
    loops: 1
  workoutFriday:
    loops: 1
  workoutSaturday:
    loops: 1
  worm:
    category: animals
    loops: 1
  yogaWednesday:
    loops: 1
  yogaThursday:
    loops: 1
  yogaFriday:
    loops: 1
  yogaSaturday:
    loops: 1
  youDoIt:
    category: funny
    loops: 1
  zombie:
    category: actions

weights:
  all:
    _: 1
  seacomp_day:
    normal: 8
    actions: 23
    social: 10
    funny: 10
    dance: 4
    animals: 8
    rare: 2
  seacomp_night:
    normal: 4
    actions: 20
    social: 10
    trip: 8
    funny: 14
    dance: 4
    animals: 4
    rare: 2
  seacomp_over:
    trip: 2
    fin: 1

menu:
  - start: '2018-10-20T00:00:00'
    weights: seacomp_day
  - start: '2018-10-20T20:00:00'
    weights: seacomp_night
  - start: '2018-10-21T02:00:00'
    weights: seacomp_over

schedule:
  - time: '2019-07-05T19:31:00'
    label: workoutWednesday
    ad_prefix: workout
