---
intros:

outros:

walks:
  abolishice:
    category: rare
    loops: 7
  appreciate:
    category: social
  aircello:
    category: dance
    loops: 1
  airdrum:
    category: dance
    loops: 1
  airsax:
    category: dance
    loops: 1
  airtrombone:
    category: dance
    loops: 1
  airguitar_wed1:
    category: dance
  airguitar_wed2:
    category: dance    
  airguitar_wed3:
    category: dance
  airguitar_wed4:
    category: dance
  airguitar_thu1:
    category: dance
  airguitar_thu2:
    category: dance    
  airguitar_thu3:
    category: dance
  airguitar_thu4:
    category: dance   
  airguitar_fri1:
    category: dance
  airguitar_fri2:
    category: dance    
  airguitar_fri3:
    category: dance
  airguitar_fri4:
    category: dance  
  airguitar_sat1:
    category: dance
  airguitar_sat2:
    category: dance    
  airguitar_sat3:
    category: dance
  airguitar_sat4:
    category: dance  
  applaud:
    category: actions
  art:
    category: inactive
  babyshark:
    category: rare
    loops: 1
  baseball:
    category: actions
    loops: 1
  bird:
    category: animals
    loops: 1
  bike:
    category: actions
  bowl:
    category: actions
    loops: 1
  cartwheel:
    category: actions
    loops: 4
  chestbump:
    category: actions
  cocoadome:
    category: inactive
  converse:
    category: social
  corgi:
    category: funny
    loops: 8
  cube:
    category: trip
    loops: 7
    audio: trip.wav
  crabwalk:
    category: actions
  crawl:
    category: actions
  dance1:
    category: dance
    loops: 13
  dance2:
    category: dance
    loops: 13
  dance3:
    category: dance
    loops: 13
  dance4:
    category: dance
    loops: 13
  dance5:
    category: dance
    loops: 13
  dance6:
    category: dance
    loops: 13
  dance7:
    category: dance
    loops: 13
  dance8:
    category: dance
    loops: 13
  dance10:
    category: dance
    loops: 13
  dots:
    category: trip
    loops: 10
    audio: trip.wav
  elephant:
    category: animals
  fartbox:
    category: inactive
  fall:
    category: actions
  flying:
    category: actions
  frida:
    category: trip
    loops: 10
    audio: trip.wav
  hammer-time:
    category: dance
    loops: 1
  handstand:
    category: actions
  highfive:
    category: social
  home:
    category: fin
  horse:
    category: inactive
  horsebackriding:
    category: actions
  hug:
    category: social
  hug3:
    category: social
  hug4:
    category: social
  hug5:
    category: social
  hydrate:
    category: actions
  inw:
    category: funny
    audio: seacompression.wav
  jazzhands:
    category: inactive
  jump:
    category: actions
  leapfrog:
    category: actions
  meditate:
    category: inactive
    loops: 60
  natureappreciate:
    category: inactive
    loops: 7
  nyan:
    category: funny
    loops: 5
  partyrock:
    category: inactive
  piggyback:
    category: actions
  pose:
    category: funny
  presentation:
    category: inactive
  race:
    category: actions
    loops: 1
  rainbow_heart:
    category: trip
    loops: 5
    audio: trip.wav
  resilience:
    category: inactive
    loops: 17
  rowboat:
    category: actions
  run:
    category: actions
  ski:
    category: actions
  sleep:
    category: inactive
  sloth:
    category: animals
  somersault:
    category: actions
  spaceodyssea:
    category: funny
    audio: seacompression.wav
  surf:
    category: actions
  swim:
    category: actions
  tag:
    category: social
  takeoff:
    category: trip
  teleport:
    category: funny
  timewarp:
    category: inactive
    loops: 6
  turtle:
    category: animals
    loops: 12
  unicycle:
    category: actions
  vogue1:
    category: inactive
    audio: dance7.wav
  walkdress:
    category: normal
  walkpants:
    category: normal
  wheelbarrow:
    category: social
  why-cross:
    category: rare
    loops: 1
  wok:
    category: funny
  walkingtogether:
    category: social
  westworldmaze:
    category: inactive
  werewolf:
    category: animals
  weirddog:
    category: trip
    loops: 10
    audio: trip.wav
  weirdeyes:
    category: trip
    loops: 6
    audio: trip.wav
  wizard:
    category: funny
  yoga1:
    category: inactive
    loops: 1
  yoga2:
    category: inactive
    loops: 1
  yoga3:
    category: inactive
    loops: 1
  yoga4:
    category: inactive
    loops: 1
  yoga5:
    category: inactive
    loops: 1
  yoga6:
    category: inactive
    loops: 1
  yoga7:
    category: inactive
    loops: 1
  zebra:
    category: trip
    loops: 15
    audio: trip.wav
  zombie:
    category: actions

weights:
  all:
    _: 1
  seacomp_day:
    normal: 8
    actions: 23
    social: 10
    funny: 6
    dance: 4
    animals: 8
    rare: 2
  seacomp_night:
    normal: 4
    actions: 20
    social: 10
    trip: 8
    funny: 9
    dance: 4
    animals: 4
    rare: 2

schedule:
  - start: '2018-10-20T00:00:00'
    weights: seacomp_day
  - start: '2018-10-20T20:00:00'
    weights: seacomp_night
