---
intros:

outros:


walks:
  abolishice:
    category: long
    loops: 7
  airguitar:
    category: long
    loops: 20
  appreciate:
    category: social
  art:
    category: actions
  bike:
    category: actions
  bowl:
    category: actions
  businessmeeting:
    category: funny
    loops: 7
  cartwheel:
    category: actions
    loops: 4
  chestbump:
    category: actions
  converse:
    category: social
  corgi:
    category: funny
    loops: 8
  crabwalk:
    category: actions
  crawl:
    category: actions
  dance1:
    category: dance
    loops: 7
  dance2:
    category: dance
  dance3:
    category: dance
  dance4:
    category: dance
  dance5:
    category: dance
  dance6:
    category: dance
  dance7:
    category: dance
  dance8:
    category: dance
  dance9:
    category: dance
    audio: dance6.wav
  dancebattle:
    category: dance
    loops: 1
  dance_rasputin:
    category: dance
    audio: rasputin.wav
  dance_rasputin2:
    category: dance
    audio: rasputin.wav
  dance_rasputin3:
    category: dance
    audio: rasputin.wav
  dots:
    category: trip
    loops: 10
    audio: trip.wav
  elephant:
    category: animals
  fall:
    category: actions
  flying:
    category: actions
  frida:
    category: trip
    loops: 10
    audio: trip.wav
  hammer-time:
    category: long
    loops: 1
  handstand:
    category: actions
  highfive:
    category: social
  horse:
    category: animals
  horsebackriding:
    category: actions
  hug:
    category: social
  hug3:
    category: social
  hug4:
    category: social
  hug5:
    category: social
  jazzhands:
    category: actions
  jump:
    category: actions
  leapfrog:
    category: actions
  meditate:
    category: mindful
    loops: 60
  mime:
    category: actions
    loops: 2
  moonwalk:
    category: dance
    loops: 1
  natureappreciate:
    category: mindful
    loops: 7
  nyan:
    category: funny
    loops: 5
  partyrock:
    category: dance
  piggyback:
    category: actions
  pose:
    category: funny
  presentation:
    category: mindful
    loops: 1
  race:
    category: actions
    loops: 1
  rainbow_heart:
    category: trip
    loops: 5
    audio: trip.wav
  rainbow_paw_cat:
    category: trip
    loops: 10
    audio: trip.wav
  resilience:
    category: mindful
    loops: 17
  rowboat:
    category: actions
  run:
    category: actions
  ski:
    category: actions
  skip:
    category: actions
  sleep:
    category: funny
  sloth:
    category: animals
  somersault:
    category: actions
  surf:
    category: actions
  swim:
    category: actions
  tag:
    category: social
  teleport:
    category: funny
  timewarp:
    category: dance
  triptrap:
    category: funny
  turtle:
    category: animals
    loops: 12
  unicycle:
    category: actions
  vogue:
    category: dance
    audio: dance7.wav
  walkdress:
    category: normal
  walkpants:
    category: normal
  wheelbarrow:
    category: social
  why-cross:
    category: mindful
    loops: 1
  wok:
    category: funny
  walkingtogether:
    category: social
  yoga1:
    category: actions
  zombie:
    category: actions


# normal
# actions
# animals
# dance
# social
# funny
# long
# mindful

weights:
  all:
    _: 1
  monday:
    normal: 1
  tuesday:
    normal: 1
    actions: 2
    animals: 2
  wednesday:
    normal: 1
    actions: 3
    animals: 3
    social: 2
  wednesday-night:
    normal: 1
    actions: 3
    animals: 3
    social: 2
    trip: 1
  thursday:
    normal: 1
    actions: 3
    animals: 2
    social: 3
    funny: 2
    trip: 1
  friday:
    actions: 3
    animals: 1
    social: 3
    funny: 4
    long: 1
    mindful: 1
  saturday:
    actions: 3
    animals: 1
    social: 3
    funny: 3
    long: 2
    mindful: 1
  saturday-night:
    actions: 3
    animals: 1
    social: 3
    funny: 3
    long: 2
    mindful: 1
    dance: 3


schedule:
  - start: '2018-07-09T00:00:00'
    weights: monday
  - start: '2018-07-10T00:00:00'
    weights: tuesday
  - start: '2018-07-11T00:00:00'
    weights: wednesday
  - start: '2018-07-11T22:00:00'
    weights: wednesday-night
  - start: '2018-07-12T06:00:00'
    weights: thursday
  - start: '2018-07-13T00:00:00'
    weights: friday
  - start: '2018-07-14T00:00:00'
    weights: saturday
  - start: '2018-07-14T19:00:00'
    weights: saturday-night
