---
intros:

outros:
  9s-count:
    file: 9s-count.gif

walks:
  corgi:
    loops: 1
  hammer-time:
    loops: 1
  nyan:
    loops: 1
  presentation:
    loops: 1
  race:
    loops: 1
  turtle:
    loops: 12
  triptrap:
    loops: 1
  why-cross: 
    loops: 1

weights:
  A: {}


schedule:
  - start: 2018-07-09T00:00:00
    weights: A
