---
intros:

outros:

walks:
  airguitar:
    loops: 20
  businessmeeting:
    loops: 7
  corgi:
    loops: 1
  hammer-time:
    loops: 1
  meditate:
    loops: 60
  natureappreciate:
    loops: 7
  nyan:
    loops: 1
  presentation:
    loops: 1
  race:
    loops: 1
  resilience:
    loops: 17
  turtle:
    loops: 12
  triptrap:
    loops: 1
  why-cross: 
    loops: 1
  westworldmaze:
    loops: 18

weights:
  A: {}


schedule:
  - start: 2018-07-09T00:00:00
    weights: A
