---
intros:

outros:


# actions
# animals
# social
# funny
# long
# mindful

walks:
  airguitar:
    category: long
  antelope:
    category: animals
  appreciate:
    category: social
  art:
    category: actions
  bike:
    category: actions
  bowl:
    category: actions
  businessmeeting:
    category: funny
  camel:
    category: animals
  cartwheel:
    category: actions
  converse:
    category: social
  corgi:
    category: funny
    loops: 3
  crabwalk:
    category: actions
  crawl:
    category: actions
  elephant:
    category: animals
  fall:
    category: actions
  fish:
    category: animals
  flying:
    category: actions
  hammer-time:
    category: long
    loops: 1
  handstand:
    category: actions
  highfive:
    category: social
  horse:
    category: animals
  horsebackriding:
    category: actions
  hug:
    category: social
  hug3:
    category: social
  hug4:
    category: social
  hug5:
    category: social
  hummingbird:
    category: animals
  jump:
    category: actions
  leapfrog:
    category: actions
  meditate:
    category: mindful
  natureappreciate:
    category: mindful
  nyan:
    category: funny
  orca:
    category: animals
  piggyback:
    category: actions
  pose:
    category: funny
  presentation:
    category: social
    loops: 1
  race:
    category: actions
    loops: 1
  resilience:
    category: mindful
  rowboat:
    category: actions
  run:
    category: actions
  ski:
    category: actions
  sleep:
    category: funny
  sloth:
    category: animals
  surf:
    category: actions
  swim:
    category: actions
  tag:
    category: social
  teleport:
    category: funny
  triptrap:
    category: funny
  turtle:
    category: animals
    loops: 12
  walkdress:
    category: normal
  walkpants:
    category: normal
  wheelbarrow:
    category: social
  why-cross:
    category: mindful
    loops: 1
  wok:
    category: funny


weights:
  all:
    _: 1
  normal:
    normal: 1


schedule:
  - start: '2018-07-09T00:00:00'
    weights: normal
