---
intros:

outros:

walks:
  airguitar:
    loops: 20
  businessmeeting:
    loops: 7
  cartwheel:
    loops: 4
  corgi:
    loops: 3
  hammer-time:
    loops: 1
  meditate:
    loops: 60
  natureappreciate:
    loops: 7
  nyan:
    loops: 1
  presentation:
    loops: 1
  race:
    loops: 1
  resilience:
    loops: 17
  turtle:
    loops: 12
  triptrap:
    loops: 1
  why-cross:
    loops: 1
  westworldmaze:
    loops: 18

weights:
  all:
    _: 1
  normal:
    normal: 1
  tweak:
    normal: 5
    animals: 1
    joke: 1
    style: 1
  ampup:
    normal: 5
    animals: 10
    style: 5
    joke: 2
    special: 2
    trippy: 1


schedule:
  - start: '2018-07-09T00:00:00'
    weights: normal
