---
intros:

outros:


walks:
  airguitar:
    category: long
    loops: 20
  antelope:
    category: animals
  appreciate:
    category: social
  art:
    category: actions
  bike:
    category: actions
  bowl:
    category: actions
  businessmeeting:
    category: funny
    loops: 7
  camel:
    category: animals
  cartwheel:
    category: actions
    loops: 4
  converse:
    category: social
  corgi:
    category: funny
    loops: 3
  crabwalk:
    category: actions
  crawl:
    category: actions
  elephant:
    category: animals
  fall:
    category: actions
  fish:
    category: animals
  flying:
    category: actions
  hammer-time:
    category: long
    loops: 1
  handstand:
    category: actions
  highfive:
    category: social
  horse:
    category: animals
  horsebackriding:
    category: actions
  hug:
    category: social
  hug3:
    category: social
  hug4:
    category: social
  hug5:
    category: social
  hummingbird:
    category: animals
  jump:
    category: actions
  leapfrog:
    category: actions
  meditate:
    category: mindful
    loops: 60
  natureappreciate:
    category: mindful
    loops: 7
  nyan:
    category: funny
  orca:
    category: animals
  piggyback:
    category: actions
  pose:
    category: funny
  presentation:
    category: social
    loops: 1
  race:
    category: actions
    loops: 1
  resilience:
    category: mindful
    loops: 17
  rowboat:
    category: actions
  run:
    category: actions
  ski:
    category: actions
  sleep:
    category: funny
  sloth:
    category: animals
  surf:
    category: actions
  swim:
    category: actions
  tag:
    category: social
  teleport:
    category: funny
  triptrap:
    category: funny
  turtle:
    category: animals
    loops: 12
  unicycle:
    category: actions
  walkdress:
    category: normal
  walkpants:
    category: normal
  wheelbarrow:
    category: social
  why-cross:
    category: mindful
    loops: 1
  wok:
    category: funny
  walkingtogether:
    category: social
  westworldmaze:
    category: mindful
    loops: 18


# normal
# actions
# animals
# social
# funny
# long
# mindful

weights:
  all:
    _: 1
  monday:
    normal: 1
  tuesday:
    normal: 1
    actions: 2
    animals: 2
  wednesday:
    normal: 1
    actions: 3
    animals: 3
    social: 2
  thursday:
    normal: 1
    actions: 3
    animals: 2
    social: 3
    funny: 2
  friday:
    actions: 3
    animals: 1
    social: 3
    funny: 4
    long: 1
    mindful: 1
  saturday:
    actions: 3
    animals: 1
    social: 3
    funny: 3
    long: 2
    mindful: 2


schedule:
  - start: '2018-07-09T00:00:00'
    weights: monday
  - start: '2018-07-10T00:00:00'
    weights: tuesday
  - start: '2018-07-11T00:00:00'
    weights: wednesday
  - start: '2018-07-12T00:00:00'
    weights: thursday
  - start: '2018-07-13T00:00:00'
    weights: friday
  - start: '2018-07-14T00:00:00'
    weights: saturday
