---
intros:

outros:

walks:
  abolishice:
    category: rare
    loops: 7
  appreciate:
    category: social
  aircello:
    category: dance
    loops: 1
  airdrum:
    category: dance
    loops: 1
  airsax:
    category: dance
    loops: 1
  airtrombone:
    category: dance
    loops: 1
  airguitar_wed1:
    category: dance
    loops: 1
  airguitar_wed2:
    category: dance
    loops: 1    
  airguitar_wed3:
    category: dance
    loops: 1
  airguitar_wed4:
    category: dance
    loops: 1
  airguitar_thu1:
    category: dance
    loops: 1
  airguitar_thu2:
    category: dance
    loops: 1
  airguitar_thu3:
    category: dance
    loops: 1
  airguitar_thu4:
    category: dance
    loops: 1
  airguitar_fri1:
    category: dance
    loops: 1
  airguitar_fri2:
    category: dance
    loops: 1
  airguitar_fri3:
    category: dance
    loops: 1
  airguitar_fri4:
    category: dance
    loops: 1
  airguitar_sat1:
    category: dance
    loops: 1
  airguitar_sat2:
    category: dance
    loops: 1
  airguitar_sat3:
    category: dance
    loops: 1
  airguitar_sat4:
    category: dance
    loops: 1
  applaud:
    category: actions
    loops: 1
  babyshark:
    category: rare
    loops: 1
  baseball:
    category: actions
    loops: 1
  bird:
    category: animals
    loops: 1
  bike:
    category: actions
  bowl:
    category: actions
    loops: 1
  burp:
    category: actions
    loops: 1
  cartwheel:
    category: actions
    loops: 4
  cat:
    category: animals
    loops: 1
  chestbump:
    category: actions
  cocoadome:
    category: inactive
  conga:
    category: dance
    loops: 1  
  converse:
    category: social
  corgi:
    category: funny
    loops: 8
  cow:
    category: animals
    loops: 1
  cowboy:
    category: actions
    loops: 1
  cube:
    category: trip
    loops: 7
    audio: trip.wav
  crabwalk:
    category: actions
  crawl:
    category: actions
  crossingguard:
    category: actions
    loops: 1
  crossingguard-wizard:
    category: actions
    loops: 1
  cry:
    category: actions
    loops: 1
  dab:
    category: dance
    loops: 1
  daftpunk-1:
    category: funny
    loops: 1
  daftpunk-2:
    category: funny
    loops: 1
  daftpunk-3:
    category: funny
    loops: 1
  daftpunk-4:
    category: funny
    loops: 1
  dance-hustle:
    category: dance
    loops: 1
  dance-macarena:
    category: dance
    loops: 1
  dance-twerk:
    category: dance
    loops: 1
  dance-twist:
    category: dance
    loops: 1
  dancemove-chacha:
    category: dance
    loops: 1
  dancemove-cupidshuffle:
    category: dance
    loops: 1
  dancemove-hokeypokey:
    category: dance
    loops: 1
  dancemove-whipnaenae:
    category: dance
    loops: 1
  dog:
    category: animals
    loops: 1
  DFV:
    category: actions
    loops: 1
  dots:
    category: trip
    loops: 10
    audio: trip.wav
  duck:
    category: animals
    loops: 1
  elephant:
    category: animals
  fartbox:
    category: inactive
  fall:
    category: actions
    loops: 1
  flying:
    category: actions
  frida:
    category: trip
    loops: 10
    audio: trip.wav
  hadouken:
    loops: 1
  hammer-time:
    category: dance
    loops: 1
  handstand:
    category: actions
  highfive:
    category: social
  home:
    category: fin
  horsebackriding:
    category: actions
  hug:
    category: social
  hug3:
    category: social
  hug4:
    category: social
  hug5:
    category: social
  hydrate:
    category: actions
  inw:
    category: funny
    audio: seacompression.wav
  jump:
    category: actions
  karaoke-totalEclipse:
    category: dance
    loops: 1
  karaoke-tubthumping:
    category: dance
    loops: 1
  karaoke-wannaDance:
    category: dance
    loops: 1
  leapfrog:
    category: actions
  meditationWednesday:
    loops: 1
  natureappreciate:
    loops: 1
  nyan:
    category: funny
    loops: 5
  piggyback:
    category: actions
  pose:
    category: funny
  propose:
    loops: 1
  race:
    category: actions
    loops: 1
  raptor:
    loops: 1
  rainbow_heart:
    category: trip
    loops: 5
    audio: trip.wav
  rickroll:
    loops: 1
  rowboat:
    category: actions
  rps1:
    loops: 1
    audio: rps.wav
  rps2:
    loops: 1
    audio: rps.wav
  rps3:
    loops: 1
    audio: rps.wav
  rps4:
    loops: 1
    audio: rps.wav
  rps5:
    loops: 1
    audio: rps.wav
  rps6:
    loops: 1
    audio: rps.wav
  rps7:
    loops: 1
    audio: rps.wav
  rps8:
    loops: 1
    audio: rps.wav
  rps9:
    loops: 1
    audio: rps.wav
  rps10:
    loops: 1
    audio: rps.wav
  rps11:
    loops: 1
    audio: rps.wav
  rps12:
    loops: 1
    audio: rps.wav
  rps13:
    loops: 1
    audio: rps.wav
  rps14:
    loops: 1
    audio: rps.wav
  rps15:
    loops: 1
    audio: rps.wav
  rps16:
    loops: 1
    audio: rps.wav
  rps17:
    loops: 1
    audio: rps.wav
  rps18:
    loops: 1
    audio: rps.wav
  rps19:
    loops: 1
    audio: rps.wav
  rps20:
    loops: 1
    audio: rps.wav
  rps21:
    loops: 1
    audio: rps.wav
  rps22:
    loops: 1
    audio: rps.wav
  rps23:
    loops: 1
    audio: rps.wav
  rps24:
    loops: 1
    audio: rps.wav
  rps25:
    loops: 1
    audio: rps.wav
  rps26:
    loops: 1
    audio: rps.wav
  rps27:
    loops: 1
    audio: rps.wav
  run:
    category: actions
  ski:
    category: actions
  sleep:
    category: inactive
  sloth:
    category: animals
  somersault:
    loops: 1
  spaceodyssea:
    category: funny
    frame_delay: 25.0
    audio: seacompression.wav
  surf:
    category: actions
  swim:
    category: actions
  tag:
    category: social
  takeoff:
    category: trip
  teamCheer:
    loops: 1
  teleport:
    category: funny
  thankRangers:
    loops: 1
  tightrope:
    loops: 1
  toothbrush:
    loops: 1
  tongueTwister1:
    loops: 1
    audio: tongueTwister.wav
  tongueTwister2:
    loops: 1
    audio: tongueTwister.wav
  tongueTwister3:
    loops: 1
    audio: tongueTwister.wav
  tongueTwister4:
    loops: 1
  turtle:
    category: animals
    loops: 12
  unicycle:
    category: actions
  vacuum:
    loops: 1
  walkBackwards:
    loops: 1
  walkdress:
    category: normal
  walkingLunge:
    loops: 1
  walkingtogether:
    category: social
  walkpants:
    category: normal
  werewolf:
    category: animals
  weirddog:
    category: trip
    loops: 10
    audio: trip.wav
  weirdeyes:
    category: trip
    loops: 6
    audio: trip.wav
  why-cross:
    category: rare
  witch:
    loops: 1
  wizard:
    category: funny
  wok:
    category: funny
  workoutWednesday:
    loops: 1
  worm:
    loops: 1
  yogaWednesday:
    loops: 1
  youDoIt:
    loops: 1
  zebra:
    category: trip
    loops: 15
    audio: trip.wav
  zombie:
    category: actions

weights:
  all:
    _: 1
  seacomp_day:
    normal: 8
    actions: 23
    social: 10
    funny: 10
    dance: 4
    animals: 8
    rare: 2
  seacomp_night:
    normal: 4
    actions: 20
    social: 10
    trip: 8
    funny: 14
    dance: 4
    animals: 4
    rare: 2
  seacomp_over:
    trip: 2
    fin: 1

schedule:
  - start: '2018-10-20T00:00:00'
    weights: seacomp_day
  - start: '2018-10-20T20:00:00'
    weights: seacomp_night
  - start: '2018-10-21T02:00:00'
    weights: seacomp_over
