---
- name: Install python packages
  apt:
    name:
      - python3-flask
      - python3-gpiozero
      - python3-requests
      - python3-yaml
    state: present

- name: Create crosswalk user
  user:
    name: crosswalk
    home: '{{crosswalk_home}}'
    shell: /usr/sbin/nologin

- name: Create service directory
  file:
    path: '{{crosswalk_home}}'
    state: directory
    owner: crosswalk
    group: crosswalk
    mode: '0755'

- name: Create bin directory
  file:
    path: '{{crosswalk_home}}/bin'
    state: directory
    owner: crosswalk
    group: crosswalk
    mode: '0755'

- name: Copy driver binaries
  copy:
    src: '{{led_driver_src}}/{{item}}'
    dest: '{{crosswalk_home}}/bin/{{item | basename}}'
    remote_src: true
    owner: crosswalk
    group: crosswalk
    mode: '0755'
  with_items:
    - 'examples-api-use/demo'
    - 'utils/led-image-viewer'

- name: Create code directory
  file:
    path: '{{crosswalk_home}}/code'
    state: directory
    owner: crosswalk
    group: crosswalk
    mode: '0755'

- name: Copy crosswalk code
  copy:
    src: "../../../../{{item}}"
    dest: "{{crosswalk_home}}/code/"
    owner: crosswalk
    group: crosswalk
    #mode: '0755'
  with_items:
    - xwalk
    - templates
    - config.yml
    - button.py
    - run.py
  notify:
    - Restart crosswalk

- name: Set audio mixer default
  copy:
    src: asound.state
    dest: /var/lib/alsa/asound.state
    owner: root
    group: root
    mode: '0644'

- name: Set default soundcard
  copy:
    src: asound.conf
    dest: /etc/asound.conf
    owner: root
    group: root
    mode: '0644'

- name: Write button service unit
  template:
    src: button.service
    dest: /lib/systemd/system/button.service
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart button

- name: Enable button service
  systemd:
    name: button
    state: started
    enabled: true
    daemon_reload: true

- name: Write crosswalk service unit
  template:
    src: crosswalk.service
    dest: /lib/systemd/system/crosswalk.service
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart crosswalk

- name: Enable crosswalk service
  systemd:
    name: crosswalk
    state: started
    enabled: true
    daemon_reload: true
