---
- name: Install python packages
  apt:
    name: 'python3-{{item}}'
    state: present
  with_items:
    - flask
    - gpiozero
    - requests
    - yaml

- name: Create crosswalk user
  user:
    name: crosswalk
    home: '{{crosswalk_home}}'
    shell: /usr/sbin/nologin

- name: Create service directory
  file:
    path: '{{crosswalk_home}}'
    state: directory
    owner: crosswalk
    group: crosswalk
    mode: '0755'

- name: Create bin directory
  file:
    path: '{{crosswalk_home}}/bin'
    state: directory
    owner: crosswalk
    group: crosswalk
    mode: '0750'

- name: Copy driver binaries
  copy:
    src: '{{led_driver_src}}/{{item}}'
    dest: '{{crosswalk_home}}/bin/'
    remote_src: true
    owner: crosswalk
    group: crosswalk
    mode: '0755'
  with_items:
    - 'examples-api-use/demo'
    - 'utils/led-image-viewer'

- name: Clone crosswalk repo
  git:
    repo: '{{crosswalk_src}}'
    dest: '{{crosswalk_home}}/code'
    version: '{{crosswalk_version}}'
  notify:
    - Restart crosswalk

- name: Write crosswalk service unit
  template:
    src: crosswalk.service
    dest: /lib/systemd/system/crosswalk.service
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart crosswalk

- name: Enable crosswalk service
  systemd:
    name: crosswalk
    state: started
    enabled: true
    daemon_reload: true
