---
- name: Install flask
  apt:
    name: 'python3-flask'
    state: present

- name: Install yaml
  apt:
    name: 'python3-yaml'
    state: present

- name: Create crosswalk user
  user:
    name: crosswalk
    home: '{{crosswalk_home}}'
    shell: /usr/sbin/nologin

- name: Create service directory
  file:
    path: '{{crosswalk_home}}'
    state: directory
    owner: crosswalk
    group: crosswalk
    mode: '0755'

- name: Create bin directory
  file:
    path: '{{crosswalk_home}}/bin'
    state: directory
    owner: crosswalk
    group: crosswalk
    mode: '0750'

- name: Copy driver binaries
  copy:
    src: '{{led_driver_src}}/{{item}}'
    dest: '{{crosswalk_home}}/bin/'
    remote_src: true
    owner: root
    group: root
    mode: '04755'
  with_items:
    - 'examples-api-use/demo'
    - 'utils/led-image-viewer'

- name: Clone crosswalk repo
  git:
    repo: '{{crosswalk_src}}'
    dest: '{{crosswalk_home}}/code'
  notify:
    - Restart crosswalk

- name: Write crosswalk service unit
  template:
    src: crosswalk.service
    dest: /etc/systemd/system/crosswalk.service
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart crosswalk

- name: Ensure crosswalk is started
  service:
    name: crosswalk
    state: started
