---
- name: Set audio mixer default
  copy:
    src: asound.state
    dest: /var/lib/alsa/asound.state
    owner: root
    group: root
    mode: '0644'

- name: Set default soundcard
  copy:
    src: asound.conf
    dest: /etc/asound.conf
    owner: root
    group: root
    mode: '0644'

- name: Quiet hours entry cron
  cron:
    name: "start quiet hours"
    hour: '2-7'
    minute: '*/10'
    job: 'amixer -c 1 set Speaker 50\%'

- name: Quiet hours exit cron
  cron:
    name: "stop quiet hours"
    hour: '8-22'
    minute: '*/10'
    job: 'amixer -c 1 set Speaker 90\%'
